# System of linear equations

In [2]:
import numpy as np
import pandas as pd
import math

# Gaussian method

In [8]:
A = np.array([
    [6, 1, 5],
    [-1, 6, 1],
    [1, 2, 5]
              ])
inverseA = np.linalg.inv(A)
print(inverseA)

[[ 0.20895522  0.03731343 -0.21641791]
 [ 0.04477612  0.18656716 -0.08208955]
 [-0.05970149 -0.08208955  0.2761194 ]]


In [7]:
A = np.array([
    [6, 1, 5],
    [-1, 6, 1],
    [1, 2, 5]
              ])

b = np.array([9.21, 4.41, 12.29])
determinantA = np.linalg.det(A)
inverseA = np.linalg.inv(A)
equations = []
x = [0, 0, 0]
while len(A) != 1:
    coeff = []
    for i in range(1, len(A)):
        coeff.append(A[0, i] / A[0, 0])
    coeff.append(b[0] / A[0, 0])
    equations.append([c for c in coeff])
    A = np.delete(A, 0, 0)
    leadCoeff = A[:, 0]
    A = np.delete(A, 0, 1)
    b = np.delete(b, 0)
    for i in range(len(A)):
        for j in range(len(A)):
            A[i, j] = A[i, j] - leadCoeff[i] * coeff[j]
        b[i] = b[i] - leadCoeff[i] * coeff[-1]

In [3]:
x[2] = b[0] / A[0]
x[1] = equations[1][1] - equations[1][0] * x[2]
x[0] = equations[0][2] - equations[0][0] * x[1] - equations[0][1] * x[2]

In [4]:
for i, answer in enumerate(x):
    print("x%s = %s" % (i + 1, float(answer)))

x1 = 0.5644777388143936
x2 = 1.625186829362499
x3 = 0.390834058532871


In [5]:
print(f'Det(A) = {determinantA}')

Det(A) = -614.3286229999994


In [6]:
print(inverseA)

[[ 0.05558149 -0.07054449  0.029591  ]
 [ 0.01600691  0.07955123  0.09169587]
 [ 0.10110436  0.07434083 -0.07064118]]


## Square root method

In [21]:
A = np.array([
    [6.43, 1.12, 0.95, 1.32, 0.83],
    [1.12, 3.03, 2.12, 0.57, 0.91],
    [0.95, 2.12, 7.38, 1.29, 1.57],
    [1.32, 0.57, 1.29, 3.32, 1.25],
    [0.83, 0.91, 1.57, 1.25, 6.46]
])

b = np.array([7.94, 3.21, 2.53, 6.25, 6.70])

In [12]:
A = np.array([
    [6.93, 1.12, 0.95, 1.32, 0.83],
    [1.12, 2.53, 2.12, 0.57, 0.91],
    [0.95, 2.12, 7.88, 1.29, 1.57],
    [1.32, 0.57, 1.29, 2.82, 1.25],
    [0.83, 0.91, 1.57, 1.25, 6.96]
])

b = np.array([8.64, 3.21, 1.83, 6.25, 7.4])

In [22]:
print(A)

[[6.43 1.12 0.95 1.32 0.83]
 [1.12 3.03 2.12 0.57 0.91]
 [0.95 2.12 7.38 1.29 1.57]
 [1.32 0.57 1.29 3.32 1.25]
 [0.83 0.91 1.57 1.25 6.46]]


In [23]:
t = np.eye(5, 5)    
for i in range(len(A)):
    for j in range(i, len(A)):
        if i == j:
            sumOfT = 0
            for k in range(i):
                sumOfT += t[k, j]**2
            t[i, j] = math.sqrt(A[i , j] - sumOfT)
        elif i < j:
            multOfT = 0
            for k in range(i):
                multOfT += t[k, i] * t[k, j]
            t[i, j] = (A[i, j] - multOfT) / t[i, i]

In [24]:
print(t)

[[2.53574447 0.44168488 0.37464343 0.52055718 0.32732005]
 [0.         1.68372042 1.16083741 0.20197995 0.45460498]
 [0.         0.         2.42736458 0.35450414 0.37886737]
 [0.         0.         0.         1.69780774 0.50269535]
 [0.         0.         0.         0.         2.39790592]]


In [25]:
tt = t.transpose()
print(tt)

[[2.53574447 0.         0.         0.         0.        ]
 [0.44168488 1.68372042 0.         0.         0.        ]
 [0.37464343 1.16083741 2.42736458 0.         0.        ]
 [0.52055718 0.20197995 0.35450414 1.69780774 0.        ]
 [0.32732005 0.45460498 0.37886737 0.50269535 2.39790592]]


In [26]:
y = []
for i in range(len(tt)):
    mult = 0
    for j in range(i):
        mult += tt[i, j] * y[j]
    y.append((b[i] - mult) / tt[i, i])

In [27]:
print(y)

[3.1312303366986436, 1.0850868514344996, 0.04008286149888717, 2.5837084587019046, 1.6129887767857682]


In [28]:
x = []

for i in range(len(t) - 1, -1, -1):
    mult = 0
    k = 0
    for j in range(len(t) - 1, i, -1):
        mult += t[i, j] * x[k]
        k += 1
    x.append((y[i] - mult) / t[i, i])

In [29]:
x.reverse()
print(x)

[0.8312950949181156, 0.4983516562563084, -0.28164048550084414, 1.3226247837278757, 0.6726655799692267]


# Simple iteration method

In [3]:
A = np.array([
    [5.5, 2.2, 1.2],
    [2.2, 5.5, -1.5],
    [1.2, -1.5, 6.6]
])

b = np.array([1.5, 0.8, 6])
x1 = [3]
x2 = [3.8]
x3 = [2]
e1 = [0]
e2 = [0]
e3 = [0]
i = 0
while True:
    x1.append((b[0] - A[0, 1] * x2[i] - A[0, 2] * x3[i]) / A[0, 0]) 
    x2.append((b[1] - A[1, 0] * x1[i] - A[1, 2] * x3[i]) / A[1, 1]) 
    x3.append((b[2] - A[2, 0] * x1[i] - A[2, 1] * x2[i]) / A[1, 1])
    e1.append(abs(x1[i] - x1[i - 1]))
    e2.append(abs(x2[i] - x2[i - 1]))
    e3.append(abs(x3[i] - x3[i - 1]))
    if max(e1[i + 1], e2[i + 1], e3[i + 1]) < 10**-4:
        break
    i += 1


In [4]:
data = {'x1': x1,
        'x2': x2,
        'x3': x3,
        'e(x1)': e1,
        'e(x2)': e2, 
        'e(x3)': e3}
df = pd.DataFrame(data)

In [5]:
df

x1        x2        x3     e(x1)     e(x2)     e(x3)
0   3.000000  3.800000  2.000000  0.000000  0.000000  0.000000
1  -1.683636 -0.509091  1.472727  4.683636  4.309091  0.527273
2   0.155041  1.220562  1.319405  4.683636  4.309091  0.527273
3  -0.503368  0.443276  1.389962  1.838678  1.729653  0.153322
4  -0.207848  0.725882  1.321628  0.658409  0.777286  0.070557
5  -0.305981  0.589038  1.334226  0.295520  0.282607  0.068334
6  -0.253992  0.631727  1.318315  0.098133  0.136845  0.012597
7  -0.267596  0.606592  1.318614  0.051989  0.042689  0.015910
8  -0.257607  0.612115  1.314728  0.013604  0.025135  0.000299
9  -0.258968  0.607059  1.314055  0.009989  0.005523  0.003887
10 -0.256799  0.607420  1.312973  0.001361  0.005055  0.000673
11 -0.256708  0.606258  1.312598  0.002169  0.000361  0.001082
12 -0.256161  0.606119  1.312261  0.000092  0.001163  0.000375
13 -0.256032  0.605808  1.312104  0.000547  0.000139  0.000337
14 -0.255873  0.605714  1.311991  0.000129  0.000311  0.000157
15 -0.255811  0.605620  1.311931  0.000159  0.000095  0.000113
16 -0.255760  0.605578  1.311891  0.000062  0.000094  0.000060

In [2]:
A = np.array([
    [6.43, 1.12, 0.95, 1.32, 0.83],
    [1.12, 5.03, 2.12, 0.57, 0.91],
    [0.95, 2.12, 7.38, 1.29, 1.57],
    [1.32, 0.57, 1.29, 3.32, 1.25],
    [0.83, 0.91, 1.57, 1.25, 6.46]
])

b = np.array([7.94, 3.21, 2.53, 6.25, 6.70])
x1 = [7.94]
x2 = [3.21]
x3 = [2.53]
x4 = [6.25]
x5 = [6.70]
e1 = [0]
e2 = [0]
e3 = [0]
e4 = [0]
e5 = [0]
i = 0
while True:
    x1.append((b[0] - A[0, 1] * x2[i] - A[0, 2] * x3[i] - A[0, 3] * x4[i] - A[0, 4] * x5[i]) / A[0, 0]) 
    x2.append((b[1] - A[1, 0] * x1[i] - A[1, 2] * x3[i] - A[1, 3] * x4[i] - A[1, 4] * x5[i]) / A[1, 1]) 
    x3.append((b[2] - A[2, 0] * x1[i] - A[2, 1] * x2[i] - A[2, 3] * x4[i] - A[2, 4] * x5[i]) / A[2, 2])
    x4.append((b[3] - A[3, 0] * x1[i] - A[3, 1] * x2[i] - A[3, 2] * x3[i] - A[3, 4] * x5[i]) / A[3, 3])
    x5.append((b[4] - A[4, 0] * x1[i] - A[4, 1] * x2[i] - A[4, 2] * x3[i] - A[4, 3] * x4[i]) / A[4, 4])
    e1.append(abs(x1[i] - x1[i - 1]))
    e2.append(abs(x2[i] - x2[i - 1]))
    e3.append(abs(x3[i] - x3[i - 1]))
    e4.append(abs(x4[i] - x4[i - 1]))
    e5.append(abs(x5[i] - x5[i - 1]))
    if max(e1[i + 1], e2[i + 1], e3[i + 1], e4[i + 1], e5[i + 1]) < 10**-4:
        break
    i += 1

7.94


In [6]:
data = {'x1': x1,
        'x2': x2,
        'x3': x3,
        'x4': x4,
        'x5': x5,
        'e(x1)': e1,
        'e(x2)': e2, 
        'e(x3)': e3,
        'e(x4)': e4,
        'e(x5)': e5}
df = pd.DataFrame(data)

In [9]:
df

x1        x2        x3        x4        x5     e(x1)     e(x2)  \
0   7.940000  3.210000  2.530000  6.250000  6.700000  0.000000  0.000000   
1  -1.845988 -4.116481 -4.119201 -5.331084 -2.259427  9.785988  7.326481   
2   3.946509  3.798212  3.175478  5.774443  3.886868  9.785988  7.326481   
3  -1.583059 -2.936498 -3.092521 -3.035941 -1.894045  5.792497  7.914693   
4   3.070960  2.980763  2.323753  4.930828  2.993241  5.529568  6.734711   
..       ...       ...       ...       ...       ...       ...       ...   
82  0.861271  0.265745 -0.221570  1.321953  0.687186  0.000094  0.000118   
83  0.861200  0.265656 -0.221652  1.321834  0.687111  0.000082  0.000102   
84  0.861261  0.265734 -0.221580  1.321938  0.687176  0.000071  0.000089   
85  0.861208  0.265667 -0.221642  1.321848  0.687120  0.000062  0.000077   
86  0.861254  0.265725 -0.221588  1.321926  0.687169  0.000054  0.000067   

       e(x3)      e(x4)     e(x5)  
0   0.000000   0.000000  0.000000  
1   6.649201  11.581084  8.959427  
2   6.649201  11.581084  8.959427  
3   7.294679  11.105527  6.146295  
4   6.267999   8.810384  5.780913  
..       ...        ...       ...  
82  0.000109   0.000158  0.000099  
83  0.000094   0.000137  0.000086  
84  0.000082   0.000119  0.000074  
85  0.000071   0.000103  0.000065  
86  0.000062   0.000090  0.000056  

[87 rows x 10 columns]

## Prohonkiy method

In [9]:
a = np.array([
    [6.43, 1.12, 0, 0, 0],
    [1.12, 3.03, 2.12, 0, 0],
    [0, 2.12, 7.38, 1.29, 0],
    [0, 0, 1.29, 3.32, 1.25],
    [0, 0, 0, 1.25, 6.46]
])

b = np.array([7.94, 3.21, 2.53, 6.25, 6.70])

In [10]:
y = [6.43]
al = [-a[0, 1] / y[0]]
bt = [b[0] / y[0]]
for i in range(1, len(a)):
    y.append(a[i, i] + a[i, i - 1] * al[i - 1])
    bt.append((b[i] - a[i, i - 1] * bt[i - 1]) / y[i])
    if i + 1 == len(a):
        continue
    al.append(-a[i, i + 1] / y[i])

In [11]:
al.append(0)
data = {
    'Alpha': al,
    'Beta': bt
}

In [12]:
df = pd.DataFrame(data)
df.index = np.arange(1, len(df) + 1)
df

Alpha      Beta
1 -0.174184  1.234837
2 -0.747818  0.644458
3 -0.222620  0.200833
4 -0.412158  1.975365
5  0.000000  0.711679

In [13]:
x = []
x.append(bt[-1])

In [14]:
j = 0
for i in range(3, -1, -1):
    x.append(al[i] * x[j] + bt[i])
    j += 1

In [19]:
data = {'x': x}
df = pd.DataFrame(data)
df.index = np.arange(1, len(x) + 1)
df

x
1  0.711679
2  1.682041
3 -0.173623
4  0.774297
5  1.099967