In [2]:
import os
import numpy as np
import pandas as pd
from sympy import Symbol, solve

In [3]:
A = np.array([
    [3.18, 1.12, 0.95, 1.32, 0.83],
    [1.12, 4.05, 2.12, 0.57, 0.91],
    [0.95, 2.12, 3.13, 1.29, 1.57],
    [1.32, 0.57, 1.29, -0.43, 1.25],
    [0.83, 0.91, 1.57, 1.25, 3.21]
])

In [3]:
print(A)

[[ 3.18  1.12  0.95  1.32  0.83]
 [ 1.12  4.05  2.12  0.57  0.91]
 [ 0.95  2.12  3.13  1.29  1.57]
 [ 1.32  0.57  1.29 -0.43  1.25]
 [ 0.83  0.91  1.57  1.25  3.21]]


In [4]:
n = len(A)
f = A
s = np.identity(n)

In [5]:
for i in range(n - 1):
    m = np.identity(n)
    m[n - 2 - i][:] = f[n - 1 - i][:]
    f = np.dot(m, f)
    f = np.dot(f, np.linalg.inv(m)) 
    s = np.dot(s, np.linalg.inv(m))

In [6]:
print(f[0][:])

[ 13.14       -47.0023      35.198168    70.49172687 -77.40956651]


In [53]:
print(s)

[[-0.23505611  2.46787965 -4.45858975 -4.22927376  7.46693337]
 [ 0.06779018 -0.63997321  0.69355106  1.47528532 -0.80485063]
 [ 0.12724954 -1.42185431  3.30922958  0.91958158 -5.20274101]
 [-0.05309942  0.61307742 -1.70079394  1.3792356  -0.40546979]
 [ 0.          0.          0.          0.          1.        ]]


In [54]:
p = f[0][:]
print(p)

[ 13.14       -47.0023      35.198168    70.49172687 -77.40956651]


In [55]:
x = Symbol('x')
Lambda = solve(x**5 - p[0] * x**4 - p[1] * x**3 - p[2] * x**2 - p[3] * x - p[4], x)

In [56]:
print(Lambda)

[-1.20112641174683, 1.15861085461439, 2.50253426845358, 2.83237840332966, 7.84760288534920]


In [57]:
l = max(Lambda)
y = [l**i for i in range(n - 1, -1, -1)]
x = np.dot(s,y)
r = np.dot(A, x) - l * x

In [58]:
print(x)

[0.909632426092779 1.29745733368176 1.25802166320717 0.581462229445302
 1.00000000000000]


In [60]:
print(l)

7.84760288534920
